# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build Client
        run: cd /home/ubuntu/actions-runner/music-inventory-web-react/music-inventory-web-react/music-inventory-web-react/client && npm install
      - name: Move Client Files to API
        run: pwd && cd /home/ubuntu/actions-runner/music-inventory-web-react/music-inventory-web-react/music-inventory-web-react/client && CI=false && npm run deploy-build && pwd
      - name: Build with Maven
        run: cd /home/ubuntu/actions-runner/music-inventory-web-react/music-inventory-web-react/music-inventory-web-react && mvn -B package --file api/pom.xml
      - name: Remove Old Docker Container
        run: sudo docker stop miw-react && sudo docker rm miw-react && sudo docker image rm miw-react
        continue-on-error: true
      - name: Build Docker Container
        run: cd /home/ubuntu/actions-runner/music-inventory-web-react/music-inventory-web-react/music-inventory-web-react/api && sudo docker build . -t miw-react && sudo docker run -p 80:80 --name miw-react -d miw-react && sudo docker update miw-react --restart=always
